# Проект 01 – Python 

## Инвертированный индекс

Информационный поиск (Information Retrieval) — это область компьютерных наук, которая изучает методы поиска нужной
информации в больших коллекциях данных. Классический пример — поисковые системы в интернете, которые позволяют найти 
документы, статьи или веб-страницы по ключевым словам.

Цель информационного поиска — не просто найти документы, содержащие слово, но и оценить их релевантность запросу 
пользователя. Одним из основных инструментов в информационном поиске является **инвертированный индекс**.

**Инвертированный индекс** — это структура данных, которая для каждого уникального слова хранит список документов или 
частей текста, где это слово встречается. Проще говоря, он «переворачивает» данные: вместо списка документов с их 
словами создаётся список слов с привязкой к документам.

<center><img src="../misc/inverted_index_scheme.png" alt="inverted_index_scheme.png" width="600"/>

### Задание 1.1. Разделение на предложения
* Считай текст книги **«Война и мир»** из `.txt` [файла](datasets/war_and_peace.txt)
* Раздели текст на предложения по знакам `. ! ?`, удали пробелы и пустые строки
* Посмотри на полученные предложения и приведи несколько примеров, когда разбиение некорреткное
* Раздели текст на предложения с помощью библиотеки [razdel](https://github.com/natasha/razdel)
* Выведи количество предложений, полученных с помощью `razdel`

In [1]:
import re

In [2]:
book_path = "../project-1/datasets/war_and_peace.txt"

In [3]:
with open(book_path, "r", encoding="utf-8") as f:
    text = f.read()

In [4]:
sentences = re.split("[.?!]", text)
sentences = [s.strip() for s in sentences if s.strip()]

In [5]:
from razdel import sentenize

In [6]:
sentences = [s.text for s in sentenize(text)]

In [7]:
len(sentences)

30255

### Задание 1.2. Очистка текста
* Очисти текст от знаков препинания и приведи все слова к **нижнему регистру**
* Разбей каждое предложение на список слов
* Удали **стоп-слова** из [файла](datasets/stop_words_russian.txt)
* Удали все пустые предложения (те, что после очистки не содержат слов)
* Выведи:
  * **количество слов** в самом длинном предложении
  * **общее количество предложений**, оставшихся после очистки.

In [8]:
stopwords_path = "../project-1/datasets/stop_words_russian.txt"

In [9]:
with open(stopwords_path, "r", encoding="utf-8") as f:
    stopwords = set(word.strip() for word in f)

In [10]:
processed_sentences = []
for sent in sentences:
    # удалить всё, кроме букв и пробелов
    clean_sent = re.sub(r"[^а-яА-ЯёЁa-zA-Z ]", " ", sent)
    # нижний регистр
    clean_sent = clean_sent.lower()
    # разбить на слова
    words = clean_sent.split()
    # удалить стоп-слова
    words = [w for w in words if w not in stopwords]
    if words:
        processed_sentences.append(words)

In [11]:
len(processed_sentences)

29620

In [12]:
longest_sentence = max(processed_sentences, key=len)

In [13]:
print("Самое длинное предложение (количество слов:", len(longest_sentence), "):")

Самое длинное предложение (количество слов: 136 ):


In [14]:
print(" ".join(longest_sentence))

граф растопчин стыдил уезжали вывозил присутственные места выдавал годное оружие пьяному сброду поднимал образа запрещал августину вывозить мощи иконы захватывал частные подводы бывшие москве ста тридцати шести подводах увозил делаемый леппихом воздушный шар намекал сожжет москву рассказывал сжег свой дом написал прокламацию французам торжественно упрекал разорили детский приют принимал славу сожжения москвы отрекался приказывал народу ловить шпионов приводить упрекал народ высылал французов москвы оставлял городе жу обер шальме составлявшую центр французского московского населения особой вины приказывал схватить увезти ссылку старого почтенного почт директора ключарева сбирал народ горы драться французами отделаться народа отдавал убийство человека уезжал задние ворота переживет несчастия москвы писал альбомы французски стихи своем участии деле понимал значения совершающегося события хотел сделать удивить совершить патриотически геройское мальчик резвился величавым неизбежным событием

### Задание 1.3. Построение инвертированного индекса
Реализуй **инвертированный индекс** для поиска слов в предложениях с помощью класса `InvertedIndex`.

**Что нужно сделать:**

* Реализуй метод `build_index`, который строит индекс из списка документов, где каждый документ — это список слов.
  * Для каждого уникального слова сохраняй список id документов (предложений), в которых оно встречается.
  * Используй атрибут `word2doc` для хранения данных.
* Реализуй метод `save_index`, чтобы **сохранять индекс в файл** (например, с помощью `pickle`) для последующего использования.
* Реализуй метод `load_index`, чтобы **загружать индекс из файла**.
* Реализуй метод `__len__`, который возвращает **количество уникальных слов** в индексе.

**Протестируй работу индекса:**

1. Построй индекс на списке предложений книги.
2. **Сохрани** индекс в файл.
3. **Загрузи** индекс из файла в **новый объект**.
4. Выведи количество **уникальных слов** в загруженном индексе

In [15]:
from typing import List
from collections import defaultdict

In [16]:
class InvertedIndex:
    """Класс для инвертированного индекса"""

    def __init__(self):
        self.word2doc = defaultdict(list)

    def build_index(self, documents: List[str]):
        """
        Построение инвертированного индекса из списка документов
        documents: список, где каждый элемент — список слов в предложении
        """
        pass

    def save_index(self, filepath: str):
        """Сохранение индекса на диск"""
        pass

    def load_index(self, filepath: str):
        """Загрузка индекса с диска"""
        pass

In [17]:
import pickle

In [18]:
class InvertedIndex:
    """Класс для инвертированного индекса"""

    def __init__(self):
        self.word2doc = defaultdict(list)

    def __len__(self):
        return len(self.word2doc)

    def build_index(self, documents: List[List[str]]):
        """
        Реализуй построение инвертированного индекса из списка документов.
        documents: список, где каждый элемент — список слов в предложении.
        """
        self.word2doc.clear()
        for doc_id, words in enumerate(documents):
            unique_words = set(words)
            for word in unique_words:
                self.word2doc[word].append(doc_id)

    def query(self, words: List[str]) -> List[int]:
        """
        Реализуй поиск предложений, содержащих все слова из списка words.
        Возвращает список id предложений, отсортированный по возрастанию.
        """
        if not words:
            return []

        # Начинаем с множества документов первого слова
        result_set = set(self.word2doc.get(words[0], []))
        for word in words[1:]:
            result_set &= set(self.word2doc.get(word, []))  # пересечение множеств

        return sorted(result_set)

    def save_index(self, filepath: str):
        """Реализуй сохранение индекса на диск"""
        with open(filepath, "wb") as f:
            pickle.dump(self.word2doc, f)

    def load_index(self, filepath: str):
        """Реализуй загрузку индекса с диска"""
        with open(filepath, "rb") as f:
            self.word2doc = pickle.load(f)

In [19]:
index = InvertedIndex()
index.build_index(processed_sentences)

In [20]:
index.save_index("index.pkl")

In [21]:
index2 = InvertedIndex()

In [22]:
index2.load_index("index.pkl")

In [23]:
len(index2)

51639

### Задание 1.4. Поиск по индексу
* Реализуй метод `query` класса `InvertedIndex`, который выполняет поиск слов в индексе.
* Метод принимает **список слов** и возвращает список id предложений, в которых встречаются **все указанные слова** (операция «и»).
* Результат должен быть **отсортирован по возрастанию** id предложения.
* Проверь работу метода `query` на следующих примерах:
  * Слово: `университет`
  * Слова: `война` и `мир`
  * Слово: `школа`

In [24]:
index2.query(["война", "мир"])

[0, 1, 7568, 7569, 15258, 15259, 15260, 23307]

In [25]:
index2.query(["университет"])

[1013, 2387, 16480]

In [26]:
index2.query(["школа"])

[]

## Головоломка Судоку

После предыдущих заданий, где мы вспомнили базовый синтаксис Python, перейдём к изучению библиотеки **NumPy**.

**NumPy** — это мощный инструмент для работы с массивами и матрицами, который широко используется в анализе данных и 
научных вычислениях. Чтобы почувствовать себя увереннее при работе с матрицами, мы попробуем реализовать 
**решатель головоломок Судоку**.

В этом задании ты научишься:
* Работать с матрицами и массивами с помощью NumPy,
* Практиковаться в использовании базовых алгоритмов и циклов,
* Писать программу, которая решает головоломку Судоку,
* Писать **тесты для проверки корректности решения**, чтобы убедиться, что солвер работает правильно.


### Задание 2.1. Запрос по API
* Изучи API [YouDoSudoku](https://www.youdosudoku.com/) и разберитесь, как получать игры судоку и их решения.
* Напиши функцию `get_sudoku(level)`, которая принимает уровень сложности (`'easy'`, `'medium'`, `'hard'`).
* Функция должна возвращать две матрицы `numpy` размером 9×9: одну с головоломкой, другую — с полным решением.
* После запроса выведи обе матрицы, чтобы убедиться, что данные получены и преобразованы правильно.


In [27]:
import requests
import numpy as np

In [28]:
def get_sudoku(level="easy"):
    """
    Получение поля Судоку с API YouDoSudoku.
    level: "easy", "medium", "hard"
    """
    body = {
        "difficulty": level, # "easy", "medium", or "hard" (defaults to "easy")
        "solution": True, # True or False (defaults to True)
        "array": False # True or False (defaults to False)
    }
    headers =  {"Content-Type":"application/json"}
    url = f"https://youdosudoku-api.com/api/"
    response = requests.get("https://you-do-sudoku-api.vercel.app/api", json=body, headers=headers)
    if response.status_code != 200:
        raise RuntimeError("Ошибка при получении судоку")
    
    data = response.json()
    # Предполагаем, что поле возвращается в data['board']
    sudoku_list = [int(char) for char in data['puzzle']]
    sudoku_array = np.array(sudoku_list).reshape(9, 9)
    solution = [int(char) for char in data['solution']]
    solution = np.array(solution).reshape(9, 9)
    return sudoku_array, solution

In [29]:
sudoku_board, solution = get_sudoku("hard")
print(sudoku_board)

[[0 0 0 0 0 0 4 5 0]
 [0 0 0 6 3 0 0 0 7]
 [0 0 0 2 0 0 3 0 0]
 [8 0 9 0 0 0 6 0 0]
 [0 0 5 0 0 0 0 2 8]
 [0 1 0 0 0 3 0 0 0]
 [1 4 0 7 0 0 0 0 0]
 [3 0 0 0 0 5 1 8 0]
 [6 0 0 0 8 0 0 0 9]]


In [30]:
print(solution)

[[7 6 3 9 1 8 4 5 2]
 [5 2 1 6 3 4 8 9 7]
 [9 8 4 2 5 7 3 6 1]
 [8 7 9 5 4 2 6 1 3]
 [4 3 5 1 7 6 9 2 8]
 [2 1 6 8 9 3 5 7 4]
 [1 4 8 7 6 9 2 3 5]
 [3 9 7 4 2 5 1 8 6]
 [6 5 2 3 8 1 7 4 9]]


### Задание 2.2. Написание тестов
* Используя библиотеку `ipytest`, напиши тесты, которые проверяют корректность работы решения Судоку
* Каждый тест должен содержать [docstring](https://peps.python.org/pep-0257/), в котором кратко описано, какое правило Судоку он проверяет
* Один тест должен проверять одно правило Судоку

In [31]:
def solve_sudoku(board):
    """Решает судоку с помощью backtracking"""
    for i in range(9):
        for j in range(9):
            if board[i, j] == 0:
                for num in range(1, 10):
                    board[i, j] = num
                    if is_partial_valid(board, i, j):
                        if solve_sudoku(board):
                            return True
                    board[i, j] = 0
                return False
    return True

In [32]:
def is_valid_sudoku(board):
    """Проверяет корректность заполненного поля судоку"""
    for i in range(9):
        row = board[i, :]
        col = board[:, i]
        if len(np.unique(row)) != 9 or len(np.unique(col)) != 9:
            return False
    for r in range(0, 9, 3):
        for c in range(0, 9, 3):
            block = board[r:r+3, c:c+3].flatten()
            if len(np.unique(block)) != 9:
                return False
    return True

In [33]:
def is_partial_valid(board, row, col):
    """Проверяет корректность текущего частичного заполнения"""
    num = board[row, col]
    # Проверка строки и столбца
    if np.count_nonzero(board[row, :] == num) > 1:
        return False
    if np.count_nonzero(board[:, col] == num) > 1:
        return False
    # Проверка блока
    start_row, start_col = 3*(row//3), 3*(col//3)
    block = board[start_row:start_row+3, start_col:start_col+3]
    if np.count_nonzero(block == num) > 1:
        return False
    return True

In [34]:
import ipytest
ipytest.autoconfig()

def test_sudoku_solution():
    board = np.array([
        [5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]
    ])
    solved_board = board.copy()
    assert solve_sudoku(solved_board)
    assert is_valid_sudoku(solved_board)

def test_empty_board():
    board = np.zeros((9,9), dtype=int)
    solved_board = board.copy()
    assert solve_sudoku(solved_board)
    assert is_valid_sudoku(solved_board)

def test_partial_board():
    board = np.zeros((9,9), dtype=int)
    board[0,0] = 1
    board[1,1] = 2
    solved_board = board.copy()
    assert solve_sudoku(solved_board)
    assert is_valid_sudoku(solved_board)

ipytest.run()

...                                                                                          [100%]
3 passed in 0.08s


<ExitCode.OK: 0>

### Задание 2.3. Реализация алгоритма решения
* Напиши алгоритм решения Судоку. Можно использовать **brute-force (backtracking)**. Алгоритм должен заполнять все пустые клетки числами от 1 до 9, соблюдая правила Судоку для строк, столбцов и 3×3 блоков
* Проверь работу алгоритма с помощью ранее написанных тестов и убедись, что они покрывают все крайние случаи
* Получи через [YouDoSudoku API](https://www.youdosudoku.com/) по 5 примеров Судоку разной сложности, реши их своим алгоритмом и выведи на экран как исходные поля, так и решения. Проверь, что решения корректны

In [35]:
for i in range(5):
    board, sol = get_sudoku("hard")
    board_to_solve = board.copy()
    solve_sudoku(board_to_solve)
    print(f"\nПример {i+1} решение:")
    print(board_to_solve == sol)


Пример 1 решение:
[[ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]]

Пример 2 решение:
[[ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True